### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by miguelocarvajal** [axilis/react-native-responsive-layout#33]
Hello!

First I have to say this library is awesome! Looking forward to fully implementing it in our apps!

I had a question in regards to the version that's currently on NPM. It does not have the SizeInfo component and withSizeInfo HOC. Is there anything that's holding it back? Maybe something I can help with?

Thanks!

**Comment by MislavMandaric** [comment]
Hi @miguelocarvajal.

We were planning to release a v1.1 release some time ago, but we discovered couple of issues that needed to be addressed before the release. We are now ready to proceed with this release and it will be available on NPM probably today. It will include FaCC's like SizeInfo, as well as some bug fixes.

For the future, we're planning to have more frequent minor and bug fix releases, but for this release we wanted to bundle multiple fixes we had discovered with documentation improvements and repo cleanup.

Thank you for your feedback and we're looking forward to your contributions. 👍
