### ISSUE TITLE
Add advanced examples

### ISSUE THREAD

**Issue by srolija** [axilis/react-native-responsive-layout#4]
Currently, there are only simple examples which do no really showcase the real power of this framework. In order to better present them, we should consider adding multiple real-life examples. 

One of them could be large responsive from that would look good on all sizes from the small mobile phones up to the large tablets.

**Comment by jaulz** [comment]
@srolija I think my PR https://github.com/axilis/react-native-responsive-layout/pull/39 would help to better demonstrate the library. People could try it on Expo before they actually need to install the library.

**Comment by srolija** [comment]
Stale, there weren't any updates for years
